[package]
id = "io.buildpacks.ruby"
name = "Ruby Buildpack"
version = "0.0.7"
[[package.stacks]]
id = "io.buildpacks.stacks.bionic"

# this section is lost when the io.buildpacks.npm is published
[[buildpacks]]
id = "io.buildpacks.ruby-node"
name = "Ruby with Node.js Buildpack"
version = "0.0.9"

[buildpacks.order]
group = [
  { id = "io.buildpacks.node", version = "0.0.5", optional = true },
  { id = "io.buildpacks.ruby", version = "0.0.7" },
]
