[buildpack]
id = "io.buildpacks.npm-nodejs"
name = "NPM Node.js Buildpack"
version = "0.0.9"
[buildpacks.order]
group = [
   { id = "io.buildpacks.node", version = "0.0.5" },
   { path = "npm-cnb" },
]
