[package]
id = "io.buildpacks.yolo"
name = "YOLO Buildpack"
version = "0.0.9"

[package.order]
group = [
   { id = "io.buildpacks.node", version = "0.0.5" },
   { path = "." }, # this feels like infinte recursion
]

# QUESTION: how to point to the buildpack.toml in the `sample/` dir?
# or does the sample/buildpack.toml point back to this buildpack like:
#      path = "../buildpack.toml"
