[package]
id = "my-monorepo-apps"
version = "0.1"
author = "Joe"
publish = false

[[package.buildpacks]]
id = "io.buildpacks.yolo-nodejs"

[[buildpacks]]
id = "io.buildpacks.yolo-nodejs"
name = "YOLO Node.js Buildpack"
version = "0.0.9"

[[buildpacks.order]]
group = [
   { id = "io.buildpacks.node", version = "0.0.5" },
   { id = "io.buildpacks.yolo", version = "0.0.7" },
]

[[buildpacks]]
id = "io.buildpacks.yolo"
name = "YOLO Buildpack"
version = "0.0.7"
path = "./yolo-cnb/"

[[buildpacks.stacks]]
id = "io.buildpacks.stacks.bionic"
