# no chance of fat fingering the id/version
# no need to repeat metadata, or other config
# `pack create-package` can point directly at a file, or provide it's own.

[package]
id = "io.buildpacks.npm-nodejs"
name = "NPM Node.js Buildpack"
version = "0.0.9"
[package.order]
group = [
  { path = "node-cnb" },
  { path = "npm-cnb" },
]
