[package]
id = "my-monorepo-apps"
version = "0.1"
author = "Joe"
publish = false

# there's no buildpack.id so if this were pass into `pack create-package`
# it would require an id/version. but that would allow you to package
# the inline buildpack for distribution

[[package.buildpacks]]
id = "io.buildpacks.node"
version = "0.0.5"

[[package.buildpacks]]
path = "./npm-cnb/"
