[package]
id = "my-monorepo-apps"
version = "0.1"
author = "Joe"
publish = false

# it would be nice if this could just be the `[[buildpacks]]` table
# but that's used by the other thing
[[package.buildpacks]]
id = "io.buildpacks.node"
version = "0.0.5"

[[package.buildpacks]]
path = "./npm-cnb/"
