# no top-level [buildpack], but that means some repos won't work when you
# point directly at them (like using the github URL, local fs, or inline bp)
# this might weaken the ecosystem by causing broking buildpack...
# like when Rubygems allowed git gems w/o a gemspec

[management]
[[management.buildpacks]]
id = "io.buildpacks.npm-nodejs"
name = "NPM Node.js Buildpack"
version = "0.0.9"
[[management.buildpacks.order]]
group = [
   { id = "io.buildpacks.node", version = "0.0.5" },
   { id = "io.buildpacks.npm", version = "0.0.7" },
]

[[management.buildpacks]]
id = "io.buildpacks.yarn-nodejs"
name = "Yarn Node.js Buildpack"
version = "0.0.9"
[[management.buildpacks.order]]
group = [
   { id = "io.buildpacks.node", version = "0.0.5" },
   { id = "io.buildpacks.yarn", version = "0.0.7" },
]

[[management.buildpacks]]
id = "io.buildpacks.npm"
name = "NPM Buildpack"
version = "0.0.7"
path = "./npm-cnb/"

[[management.buildpacks.stacks]]
id = "io.buildpacks.stacks.bionic"

[[management.buildpacks]]
id = "io.buildpacks.yarn"
name = "Yarn Buildpack"
version = "0.0.7"
path = "./yarn-cnb/"

[[management.buildpacks.stacks]]
id = "io.buildpacks.stacks.bionic"

[[management.buildpacks]]
id = "io.buildpacks.node"
name = "Node Engine Buildpack"
version = "0.0.5"
path = "./node-cnb/"

[[management.buildpacks.stacks]]
id = "io.buildpacks.stacks.bionic"
